create table if not exists payment_flow_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'INFO',
  stage text not null,
  status text,
  event text,
  event_id text,
  ticket_id uuid,
  telegram_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists payment_flow_logs_ticket_idx on payment_flow_logs(ticket_id, created_at desc);
create index if not exists payment_flow_logs_event_idx on payment_flow_logs(event_id, created_at desc);
create index if not exists payment_flow_logs_created_idx on payment_flow_logs(created_at desc);
comment on table payment_flow_logs is 'Trazabilidad del flujo de pago del Telegram Shop: webhook recibido, matching de ticket, storage y entrega Telegram.';
